version: "3"

services:
  links-service:
    build:
      context: .
      dockerfile: Urll.Links/Dockerfile
    container_name: links-service
    ports:
      - '5001:80'

  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
